apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
  namespace: default
  labels:
    app: shop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
      annotations:
        builder: 'SoonBeom Kwon'
        prometheus.io/scrape: 'true'                         
        prometheus.io/path: '/actuator/prometheus'      
        prometheus.io/port: '8080'			 
    spec:
      containers:
        - name: shop
          image: 324410205693.dkr.ecr.ap-northeast-2.amazonaws.com/eks-on-aws-springboot
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: stage
            - name: DB_ENDPOINT
              value: eks-mysql-stage.cpkfj6v1m8li.ap-northeast-2.rds.amazonaws.com
            - name: DB_USERNAME
              value: shop
            - name: DB_PASSWORD
              value: shop
            - name: REDIS_ENDPOINT
              value: eks-redis.deo7n1.0001.apn2.cache.amazonaws.com
            - name: JAVA_TOOL_OPTIONS
              value: "-Xms1024M -Xmx1024M"
            - name: LOKI_URL
              value: http://3.38.164.8:3100/loki/api/v1/push
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: shop
  namespace: default
  labels:
    app: shop
spec:
  type: NodePort
  selector:
    app: shop
  ports:
    - port: 80
      targetPort: 8080